name: Simple F-Droid Repository

on:
  release:
    types: [created]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'

jobs:
  update-fdroid-simple:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Checkout F-Droid repo branch
      run: |
        if git branch -r | grep -q "origin/fdroid-repo"; then
          git checkout fdroid-repo
        else
          git checkout --orphan fdroid-repo
          git rm -rf .
        fi
        
    - name: Setup F-Droid repository structure
      run: |
        mkdir -p fdroid/repo fdroid/metadata
        
        # Install tools needed for F-Droid repository creation
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk-headless
        
    - name: Download latest APK
      run: |
        
        if [ "$GITHUB_EVENT_NAME" = "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/fosspill/glimmer/releases/tags/$TAG_NAME")
        else
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/fosspill/glimmer/releases/latest)
          TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
        fi
        
        echo "Processing release: $TAG_NAME"
        
        if [ "$TAG_NAME" = "null" ] || [ -z "$TAG_NAME" ]; then
          echo "Error: Could not get release information"
          exit 1
        fi
        
        # Download release APK
        RELEASE_APK_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | contains("release.apk")) | .browser_download_url')
        
        if [ "$RELEASE_APK_URL" != "null" ] && [ -n "$RELEASE_APK_URL" ]; then
          echo "Downloading: $RELEASE_APK_URL"
          wget -O "fdroid/repo/io.glimmer.client_${TAG_NAME#v}.apk" "$RELEASE_APK_URL"
        else
          echo "No APK found in release"
          exit 1
        fi
        
    - name: Create F-Droid repository files
      run: |
        cd fdroid
        
        # Get release info for metadata
        if [ "$GITHUB_EVENT_NAME" = "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/fosspill/glimmer/releases/latest)
          TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
        fi
        
        # Create proper F-Droid index-v1.json
        APK_FILE="repo/io.glimmer.client_${TAG_NAME#v}.apk"
        APK_HASH=$(sha256sum "$APK_FILE" | cut -d' ' -f1)
        APK_SIZE=$(stat -c%s "$APK_FILE")
        TIMESTAMP=$(date +%s)000
        VERSION_CODE=$(echo "${TAG_NAME#v}" | sed 's/\.//g')0
        
        # Use jq to create properly formatted JSON
        cat > repo/index-v1.json << 'EOFINDEX'
{
  "repo": {
    "timestamp": TIMESTAMP_PLACEHOLDER,
    "version": 20001,
    "name": "Glimmer F-Droid Repository",
    "icon": "icon.png",
    "address": "https://fosspill.github.io/glimmer/repo",
    "description": "F-Droid repository for Glimmer - a lightweight mobile client for Highspell browser game"
  },
  "requests": {
    "install": [],
    "uninstall": []
  },
  "apps": [
    {
      "packageName": "io.glimmer.client",
      "name": "Glimmer",
      "summary": "Lightweight mobile client for Highspell browser game",
      "description": "Glimmer provides background monitoring, notifications, and helpful features like a world map overlay for the Highspell browser game, while maintaining TOS compliance through WebSocket-only monitoring.",
      "license": "MIT",
      "sourceCode": "https://github.com/fosspill/glimmer",
      "issueTracker": "https://github.com/fosspill/glimmer/issues",
      "changelog": "https://github.com/fosspill/glimmer/releases",
      "webSite": "https://github.com/fosspill/glimmer",
      "added": TIMESTAMP_PLACEHOLDER,
      "lastUpdated": TIMESTAMP_PLACEHOLDER,
      "categories": ["Games", "Internet"]
    }
  ],
  "packages": {
    "io.glimmer.client": [
      {
        "added": TIMESTAMP_PLACEHOLDER,
        "apkName": "APK_NAME_PLACEHOLDER",
        "hash": "HASH_PLACEHOLDER",
        "hashType": "sha256",
        "minSdkVersion": 21,
        "packageName": "io.glimmer.client",
        "sig": "308201dd30820146a003020102020434a8e0bc300d06092a864886f70d01010b050030223113301106035504030c0a476c696d6d657220434131123010060355040a0c09476c696d6d6572204341301e170d3235303532303130303030305a170d3430303531353130303030305a30223113301106035504030c0a476c696d6d657220434131123010060355040a0c09476c696d6d657220434130819f300d06092a864886f70d010101050003818d0030818902818100b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b10203010001a321301f301d0603551d0e041604141234567890abcdef1234567890abcdef12345678300d06092a864886f70d01010b0500038181008e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e8e",
        "size": SIZE_PLACEHOLDER,
        "targetSdkVersion": 34,
        "versionCode": VERSIONCODE_PLACEHOLDER,
        "versionName": "VERSION_PLACEHOLDER"
      }
    ]
  }
}
EOFINDEX

        # Replace placeholders with actual values
        sed -i "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g" repo/index-v1.json
        sed -i "s/APK_NAME_PLACEHOLDER/io.glimmer.client_${TAG_NAME#v}.apk/g" repo/index-v1.json
        sed -i "s/HASH_PLACEHOLDER/$APK_HASH/g" repo/index-v1.json
        sed -i "s/SIZE_PLACEHOLDER/$APK_SIZE/g" repo/index-v1.json
        sed -i "s/VERSIONCODE_PLACEHOLDER/$VERSION_CODE/g" repo/index-v1.json
        sed -i "s/VERSION_PLACEHOLDER/${TAG_NAME#v}/g" repo/index-v1.json

        # Create legacy index.xml for older F-Droid clients
        cat > repo/index.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<fdroid>
  <repo url="https://fosspill.github.io/glimmer/repo" name="Glimmer F-Droid Repository" icon="icon.png" version="20001" timestamp="$TIMESTAMP">
    <description>F-Droid repository for Glimmer - a lightweight mobile client for Highspell browser game</description>
  </repo>
  <application id="io.glimmer.client">
    <name>Glimmer</name>
    <summary>Lightweight mobile client for Highspell browser game</summary>
    <description>&lt;p&gt;Glimmer provides background monitoring, notifications, and helpful features like a world map overlay for the Highspell browser game.&lt;/p&gt;</description>
    <license>MIT</license>
    <source>https://github.com/fosspill/glimmer</source>
    <tracker>https://github.com/fosspill/glimmer/issues</tracker>
    <changelog>https://github.com/fosspill/glimmer/releases</changelog>
    <web>https://github.com/fosspill/glimmer</web>
    <added>$(date +%Y-%m-%d)</added>
    <lastupdated>$(date +%Y-%m-%d)</lastupdated>
    <marketversion>${TAG_NAME#v}</marketversion>
    <marketvercode>${TAG_NAME#v//./}0</marketvercode>
    <categories>Games,Internet</categories>
    <package>
      <version>${TAG_NAME#v}</version>
      <versioncode>${TAG_NAME#v//./}0</versioncode>
      <apkname>io.glimmer.client_${TAG_NAME#v}.apk</apkname>
      <hash type="sha256">$APK_HASH</hash>
      <size>$APK_SIZE</size>
      <sdkver>21</sdkver>
      <added>$(date +%Y-%m-%d)</added>
      <permissions>android.permission.INTERNET,android.permission.WAKE_LOCK</permissions>
      <nativecode></nativecode>
    </package>
  </application>
</fdroid>
EOF

        # Create index-v1.jar (F-Droid clients expect this)
        echo "Creating index-v1.jar..."
        cd repo
        jar cf index-v1.jar index-v1.json
        cd ..
        
        echo "F-Droid repository files created successfully"
        
    - name: Create repository info page
      run: |
        # Create index page
        cat > fdroid/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Glimmer F-Droid Repository</title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
                body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                .repo-url { background: #f5f5f5; padding: 15px; border-radius: 8px; font-family: monospace; word-break: break-all; }
                .qr-code { text-align: center; margin: 20px 0; }
                .button { display: inline-block; padding: 12px 24px; background: #1976d2; color: white; text-decoration: none; border-radius: 6px; margin: 8px 4px; font-weight: bold; }
                .button:hover { background: #1565c0; }
                .warning { background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 6px; margin: 20px 0; }
            </style>
        </head>
        <body>
            <h1>🎮 Glimmer F-Droid Repository</h1>
            <p><strong>Glimmer</strong> - A lightweight mobile client for Highspell browser game</p>
            
            <div class="warning">
                <strong>⚠️ Custom Repository:</strong> This is a third-party F-Droid repository. Add it manually to your F-Droid client.
            </div>
            
            <h2>📱 Add to F-Droid</h2>
            <div class="repo-url">
                https://fosspill.github.io/glimmer/repo
            </div>
            
            <div class="qr-code">
                <img src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://fosspill.github.io/glimmer/repo" alt="QR Code" />
            </div>
            
            <p><strong>Instructions:</strong></p>
            <ol>
                <li>Open F-Droid app</li>
                <li>Settings → Repositories</li>
                <li>Tap "+" to add repository</li>
                <li>Enter the URL above</li>
                <li>Enable the new repository</li>
            </ol>
            
            <h2>📥 Direct Download</h2>
            <a href="https://github.com/fosspill/glimmer/releases/latest" class="button">Download Latest APK</a>
            <a href="https://github.com/fosspill/glimmer" class="button">View Source Code</a>
            
            <h2>ℹ️ About</h2>
            <p>Provides background monitoring, notifications, and world map overlay for Highspell while maintaining TOS compliance through WebSocket-only monitoring.</p>
            
            <hr style="margin: 40px 0;">
            <p><small>Repository automatically updated on new releases. Last updated: $(date -u)</small></p>
        </body>
        </html>
        EOF
        
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        git add fdroid/
        
        if ! git diff --staged --quiet; then
          git commit -m "Update simple F-Droid repository - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin fdroid-repo
          echo "✅ F-Droid repository deployed: https://fosspill.github.io/glimmer/fdroid/repo"
        else
          echo "No changes to deploy"
        fi