name: Minimal F-Droid Repository

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  simple-fdroid:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup F-Droid branch
      run: |
        if git branch -r | grep -q "origin/fdroid-repo"; then
          git checkout fdroid-repo
        else
          git checkout --orphan fdroid-repo
          git rm -rf . || true
        fi
        mkdir -p repo
        
    - name: Download latest APK
      run: |
        RELEASE=$(curl -s https://api.github.com/repos/fosspill/glimmer/releases/latest)
        APK_URL=$(echo "$RELEASE" | jq -r '.assets[] | select(.name | contains("release.apk")) | .browser_download_url')
        VERSION=$(echo "$RELEASE" | jq -r '.tag_name')
        
        if [ "$APK_URL" != "null" ]; then
          echo "Downloading $APK_URL"
          wget -O "repo/glimmer-${VERSION}.apk" "$APK_URL"
        else
          echo "No release APK found"
          exit 1
        fi
        
    - name: Create repository files
      run: |
        # Create the main info page
        cat > index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Glimmer F-Droid Repository</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }
        .repo-url { background: #f5f5f5; padding: 15px; border-radius: 8px; font-family: monospace; word-break: break-all; margin: 20px 0; }
        .qr { text-align: center; margin: 20px 0; }
        .btn { display: inline-block; padding: 12px 24px; background: #1976d2; color: white; text-decoration: none; border-radius: 6px; margin: 10px 5px; }
    </style>
</head>
<body>
    <h1>🎮 Glimmer F-Droid Repository</h1>
    <p>Lightweight mobile client for Highspell browser game</p>
    
    <h2>📱 Add to F-Droid</h2>
    <div class="repo-url">https://fosspill.github.io/glimmer/repo</div>
    
    <div class="qr">
        <img src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://fosspill.github.io/glimmer/repo" alt="QR Code" />
    </div>
    
    <p><strong>Instructions:</strong></p>
    <ol>
        <li>Open F-Droid</li>
        <li>Settings → Repositories</li>
        <li>Add the URL above</li>
    </ol>
    
    <a href="https://github.com/fosspill/glimmer/releases/latest" class="btn">Direct APK Download</a>
    
    <hr style="margin: 40px 0;">
    <p><small>Files: <a href="repo/">repo/</a> | <a href="repo/index.xml">index.xml</a> | <a href="repo/index-v1.json">index-v1.json</a></small></p>
</body>
</html>
EOF

        # Create F-Droid repository files in /repo directory
        cat > repo/index.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<fdroid>
  <repo url="https://fosspill.github.io/glimmer/repo" name="Glimmer Repository" version="1" timestamp="1703097600000">
    <description>Glimmer APK Repository</description>
  </repo>
</fdroid>
EOF

        # Create modern F-Droid index
        cat > repo/index-v1.json << 'EOF'
{
  "repo": {
    "name": "Glimmer Repository",
    "address": "https://fosspill.github.io/glimmer/repo",
    "description": "Glimmer APK Repository",
    "version": 1,
    "timestamp": 1703097600000
  },
  "apps": [],
  "packages": {}
}
EOF

        # Create the required JAR file
        cd repo
        if command -v jar > /dev/null; then
          jar cf index-v1.jar index-v1.json
        else
          # Fallback if jar is not available
          echo "jar command not found, copying JSON as fallback"
          cp index-v1.json index-v1.jar
        fi
        
        echo "Created files:"
        ls -la
        cd ..
        echo "Repository structure:"
        find . -name "*.html" -o -name "*.xml" -o -name "*.json" -o -name "*.jar" -o -name "*.apk" | head -10
        
    - name: Deploy
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        git add .
        git commit -m "Update F-Droid repository" || echo "No changes"
        git push origin fdroid-repo
        
        echo "Repository available at: https://fosspill.github.io/glimmer/repo"