name: Minimal F-Droid Repository

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  simple-fdroid:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup F-Droid branch
      run: |
        if git branch -r | grep -q "origin/fdroid-repo"; then
          git checkout fdroid-repo
        else
          git checkout --orphan fdroid-repo
          git rm -rf . || true
        fi
        mkdir -p repo
        
    - name: Download latest APK
      run: |
        RELEASE=$(curl -s https://api.github.com/repos/fosspill/glimmer/releases/latest)
        APK_URL=$(echo "$RELEASE" | jq -r '.assets[] | select(.name | contains("release.apk")) | .browser_download_url')
        VERSION=$(echo "$RELEASE" | jq -r '.tag_name')
        
        if [ "$APK_URL" != "null" ]; then
          echo "Downloading $APK_URL"
          wget -O "repo/glimmer-${VERSION}.apk" "$APK_URL"
        else
          echo "No release APK found"
          exit 1
        fi
        
    - name: Create HTML page
      run: |
        printf '<!DOCTYPE html><html><head><title>Glimmer F-Droid Repository</title></head><body><h1>Glimmer F-Droid Repository</h1><p>Add this URL to F-Droid: <code>https://fosspill.github.io/glimmer/repo</code></p><img src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://fosspill.github.io/glimmer/repo" alt="QR Code"/></body></html>' > index.html

    - name: Create F-Droid files
      run: |
        printf '<?xml version="1.0" encoding="utf-8"?><fdroid><repo url="https://fosspill.github.io/glimmer/repo" name="Glimmer Repository" version="1" timestamp="1703097600000"><description>Glimmer APK Repository</description></repo></fdroid>' > repo/index.xml
        printf '{"repo":{"name":"Glimmer Repository","address":"https://fosspill.github.io/glimmer/repo","version":1,"timestamp":1703097600000},"apps":[],"packages":{}}' > repo/index-v1.json
        cd repo && echo '{}' | jar -cMf index-v1.jar index-v1.json && cd ..
        
    - name: Deploy
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update F-Droid repository" || echo "No changes"
        git push origin fdroid-repo